
import os
import sys
import shutil
import subprocess
import argparse
from loguru import logger

# Add root directory to sys.path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from loguru import logger
logger.info("Importing separate_all_audio_under_folder...")
from tools.utils.step010_demucs_vr import separate_all_audio_under_folder
logger.info("Importing xtts_func...")
from tools.tts.step042_tts_xtts import tts as xtts_func
logger.info("Importing cosy_func...")
from tools.tts.step043_tts_cosyvoice import tts as cosy_func
logger.info("Importing vits_func...")
from tools.tts.step045_tts_vits import tts as vits_func
logger.info("Imports complete.")

def get_audio_from_video(video_path, output_folder):
    """Extract audio from video to use as speaker reference"""
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    
    # Use Demucs to separate vocals, which is better for voice cloning than full audio
    # But for simplicity and speed in this script, maybe just extracting audio first is enough?
    # Actually, the user wants "clone voice", so clean vocals are best.
    # We can reuse separate_all_audio_under_folder logic or just call it.
    
    # We need a folder structure for separate_all_audio_under_folder
    # It expects a folder containing video or audio.
    # Let's just use ffmpeg to extract audio first, then pass to demucs if needed?
    # step010_demucs_vr.separate_all_audio_under_folder takes a generic folder.
    
    # Let's create a temp folder for this video processing
    vid_name = os.path.splitext(os.path.basename(video_path))[0]
    vid_folder = os.path.join(output_folder, vid_name)
    os.makedirs(vid_folder, exist_ok=True)
    
    # Copy/Link video there? Or just pass the path if separate_... supports it?
    # separate_all_audio_under_folder iterates over files in folder.
    # So we copy video to vid_folder.
    dest_video = os.path.join(vid_folder, "download.mp4")
    if not os.path.exists(dest_video):
        shutil.copy(video_path, dest_video)
        
    # Run Demucs
    logger.info(f"Extracting vocals from {video_path}...")
    try:
        status, vocals_path, _ = separate_all_audio_under_folder(vid_folder, model_name='htdemucs_ft', device='auto', shifts=1)
        return vocals_path
    except Exception as e:
        logger.error(f"Demucs failed: {e}")
        # Fallback: extract simple audio
        audio_path = os.path.join(vid_folder, "audio.wav")
        subprocess.run(['ffmpeg', '-i', video_path, '-vn', '-acodec', 'pcm_s16le', '-ar', '24000', '-ac', '1', audio_path, '-y'], check=True)
        return audio_path

def merge_audio_video(video_path, audio_path, output_path):
    """Merge new audio with original video"""
    cmd = [
        'ffmpeg', '-i', video_path, '-i', audio_path,
        '-c:v', 'copy', '-c:a', 'aac', '-map', '0:v:0', '-map', '1:a:0',
        '-shortest', '-y', output_path
    ]
    subprocess.run(cmd, check=True)

def main():
    parser = argparse.ArgumentParser(description='Compare Voice Cloning Models')
    parser.add_argument('video_path', help='Path to input video with reference voice')
    parser.add_argument('--text', default="Hello, this is a voice cloning test generated by artificial intelligence. How do you like my voice?", help='Text to speak')
    parser.add_argument('--output_dir', default='compare_results', help='Directory to save results')
    
    args = parser.parse_args()
    
    video_path = args.video_path
    text = args.text
    output_dir = args.output_dir
    
    if not os.path.exists(video_path):
        print(f"File not found: {video_path}")
        return
        
    os.makedirs(output_dir, exist_ok=True)
    
    # 1. Get Speaker Wav
    print(f"--- Step 1: Extracting Reference Audio ---")
    speaker_wav = get_audio_from_video(video_path, os.path.join(output_dir, 'temp'))
    print(f"Reference Audio: {speaker_wav}")
    
    # 2. XTTS
    print(f"\n--- Step 2: Running XTTS ---")
    xtts_wav = os.path.join(output_dir, 'xtts_audio.wav')
    xtts_video = os.path.join(output_dir, 'xtts_result.mp4')
    try:
        # XTTS supports English
        xtts_func(text, xtts_wav, speaker_wav=speaker_wav, target_language='English') 
        if os.path.exists(xtts_wav):
            merge_audio_video(video_path, xtts_wav, xtts_video)
            print(f"XTTS Result: {xtts_video}")
    except Exception as e:
        print(f"XTTS Failed: {e}")

    # 3. CosyVoice
    print(f"\n--- Step 3: Running CosyVoice ---")
    cosy_wav = os.path.join(output_dir, 'cosy_audio.wav')
    cosy_video = os.path.join(output_dir, 'cosy_result.mp4')
    try:
        # CosyVoice supports English
        cosy_func(text, cosy_wav, speaker_wav=speaker_wav, target_language='English')
        if os.path.exists(cosy_wav):
            merge_audio_video(video_path, cosy_wav, cosy_video)
            print(f"CosyVoice Result: {cosy_video}")
    except Exception as e:
        print(f"CosyVoice Failed: {e}")

    # 4. VoxCPM (VITS)
    print(f"\n--- Step 4: Running VoxCPM ---")
    vox_wav = os.path.join(output_dir, 'vox_audio.wav')
    vox_video = os.path.join(output_dir, 'vox_result.mp4')
    try:
        # VoxCPM is primarily Vietnamese. The user claims it supports English?
        # If it is a VITS model trained on Vietnamese, it might NOT support English unless phonemizer handles it.
        # But user requested English text. I will try passing 'en' as target language if supported, 
        # or just pass English text to 'vi' setting (VITS might try to pronounce English words with Vietnamese phonemes).
        # Let's check step045 again or just try.
        # step045 tts signature: tts(..., target_language='vi')
        # If I pass 'en', step045 might ignore it or use it if multi-lingual.
        # I'll try passing 'en' purely because user asked.
        # If it fails, I'll catch it.
        vits_func(text, vox_wav, speaker_wav=speaker_wav, target_language='en') 
        if os.path.exists(vox_wav):
            merge_audio_video(video_path, vox_wav, vox_video)
            print(f"VoxCPM Result: {vox_video}")
    except Exception as e:
        print(f"VoxCPM Failed: {e}")


if __name__ == "__main__":
    main()

